### PR TITLE
Fix rotations when nutation angles are involved

### LINKED ISSUE #122: Rotations involved nutation and precession angles is wrong
# Bug report

## Describe the bug
When loading this [specific data for BODY599](https://github.com/nyx-space/anise/blob/b8b97cfd607ed2a2e97ff563b6d581a6f6785ccf/data/pck00011.tpc#L1337-L1379), I compute the alpha, delta, and twist angles to be as follows on J2000 TDB (i.e. both d and T are strictly zero, and they are respectively the days past J2000 TDB and the centuries past J2000 TDB). In the following, the cos() and sin() functions expect degrees (not radians).

```
alpha = 268.056595 - 0.006499 T + 0.000117 * sin(99.360714) + 0.000938 * sin(175.895369) + 0.001432 * sin(300.323162) + 0.00003 * sin(114.012305) + 0.00215 * sin(49.511251) = 268.0914905766866 deg = 4.679079207142533 rad
delta = 64.495303 + 0.002413 T + 0.00005 * cos(99.360714) + 0.000404 * cos(175.895369) + 0.000617 * cos(300.323162) - 0.000013 * cos(114.012305) + 0.000926 * cos(49.511251) = 64.52434928998404 deg = 1.126162342817087 rad
w = 284.95 + 870.536 d = 284.95 deg = 4.973315703557842 rad
```

Note that the expression above is printed directly [by the program](https://github.com/nyx-space/anise/blob/b8b97cfd607ed2a2e97ff563b6d581a6f6785ccf/src/structure/planetocentric/mod.rs#L191), and I believe it matches the [example from the PCK header documentation](https://github.com/nyx-space/anise/blob/b8b97cfd607ed2a2e97ff563b6d581a6f6785ccf/data/pck00011.tpc#L695).

The complete list of nutation and precession angles at T=d=0.0 are computed as followed by ANISE (numbered here as J1-J15 instead of J1-J10 and Ja-Je as in the documentation):

```
J1 = 73.32 + 91472.9 T = 73.32
J2 = 24.62 + 45137.2 T = 24.62
J3 = 283.9 + 4850.7 T = 283.9
J4 = 355.8 + 1191.3 T = 355.8
J5 = 119.9 + 262.1 T = 119.9
J6 = 229.8 + 64.3 T = 229.8
J7 = 352.25 + 2382.6 T = 352.25
J8 = 113.35 + 6070 T = 113.35
J9 = 146.64 + 182945.8 T = 146.64
J10 = 49.24 + 90274.4 T = 49.24
J11 = 99.360714 + 4850.4046 T = 99.360714
J12 = 175.895369 + 1191.9605 T = 175.895369
J13 = 300.323162 + 262.5475 T = 300.323162
J14 = 114.012305 + 6070.2476 T = 114.012305
J15 = 49.511251 + 64.3 T = 49.511251
```

The DCM returned by PXFORM differs from that that returned by ANISE:

```
thread 'orientations::validation::validate_iau_rotation_to_parent' panicked at '#0 2000-01-01T11:58:55.816072704 UTC
got:
  ┌                                                                   ┐
  │    0.2287851464637683   -0.8803183511537116  -0.41556823432447604 │
  │     0.973371541024141   0.20058701392260808   0.11096257463622777 │
  │ -0.014324799539297372  -0.42988888153524274     0.902768159413333 │
  └                                                                   ┘

want:
  ┌                                                                   ┐
  │    0.2282653328760834   -0.8802481155891952   -0.4160026355789609 │
  │    0.9734895258323475   0.19994923179133894   0.11107856589263648 │
  │ -0.014597290902157951   -0.4303295942736501    0.9025537986129101 │
  └                                                                   ┘

err: 1.101e-3', tests/orientations/validation.rs:80:13

#0 @ 2000-01-01T11:58:55.816072704 UTC unit vector angle error for body 599 IAU_JUPITER: 1.5515228172636192e-2 deg
```

To be perfectly clear, if I use the PCK 08 file, or if I set the arrays BODY599_NUT_PREC_RA and BODY599_NUT_PREC_DEC to zero, then the DCM computed by ANISE matches that computed by SPICE's PXFORM function. So I've pinpointed my issue to the computation of the nutation and precession angles.

## To Reproduce

1. Modify the `validate_iau_rotation_to_parent` test to load this file the PCK 00011 file, or enable Mercury in the PCK 00008 file.
2. Run the test, and observe it failing.

## Expected behavior
The computation by ANISE should match that of SPICE's PXFORM.

## Code to reproduce the issue
Refer to commit b8b97cfd607ed2a2e97ff563b6d581a6f6785ccf.

## Platform
Linux, Rust

## Additional context

I've contacted NAIF about this specific issue, seeking guidance.

### PR DESCRIPTION
**Pull request by ChristopherRabotin**
# Summary

+ Fix IAU_MOON, IAU_JUPITER, IAU_NEPTUNE, IAU_URANUS frames whose definitions include nutation trigonometric angles
+ Add `rss_radius_km` and `rss_velocity_km_s` to the `CartesianState` structure to quickly compute the root mean square error between two states (as long as their frames match)
+ Add `IAU_MOON` and `IAU_MOON_FRAME` NaifID and Frame constants
+ Switch implementation of the latitude calculation to a constant-time calculation, considered to be more precise. It's about 52% faster than the iterative approach (but it requires a bit more computations). This new algorithm calculates the geodetic height, latitude, and longitude all at once. It is exposed as `latlongalt`.
- Add pck11.pca to the Nyx Space cloud.
- [x] Expose the IAU_MOON and IAU_MOON_FRAME to Python

Fixes #122 .

## Architectural Changes

No change

## New Features

No change

## Improvements

Geodetic latitude is twice as fast.

## Bug Fixes

Fix planetary rotations when trigonometric polynomials are involved.

## Testing and validation

1. New test of a specific rotation of a Moon J2000 state into an IAU_MOON state, comparing the data from SPICE and that of ANISE.
2. Enable IAU rotation validation for Moon, Jupiter, Neptune, Uranus

## Documentation

This PR does not primarily deal with documentation changes.

### CODE REVIEW

File: anise/src/astro/orbit_geodetic.rs [hunk 1]
```diff
@@ -190,66 +189,62 @@ impl CartesianState {
         Ok(self.apoapsis_km()? - self.frame.mean_equatorial_radius_km()?)
     }
 
+    /// Returns the geodetic latitude, geodetic longitude, and geodetic height, respectively in degrees, degrees, and kilometers.
+    ///
+    /// # Algorithm
+    /// This uses the Heikkinen procedure, which is not iterative. The results match Vallado and GMAT.
+    ///
+    pub fn latlongalt(&self) -> PhysicsResult<(f64, f64, f64)> {
+        let a = self.frame.mean_equatorial_radius_km()?;
```
Comment (ChristopherRabotin) [inline anise/src/astro/orbit_geodetic.rs:198]: Add units to these variables, add permalink to the algorithm on Wikipedia, and consider updating Wikipedia with units and additional explanation.

File: anise/src/astro/orbit_geodetic.rs [hunk 2]
```diff
@@ -190,66 +189,62 @@ impl CartesianState {
...
+    }
+
     /// Returns the geodetic longitude (λ) in degrees. Value is between 0 and 360 degrees.
     ///
     /// # Frame warning
-    /// If the state is NOT in a body fixed frame (i.e. ITRF93), then this computation is INVALID.
-    ///
-    /// Although the reference is not Vallado, the math from Vallado proves to be equivalent.
-    /// Reference: G. Xu and Y. Xu, "GPS", DOI 10.1007/978-3-662-50367-6_2, 2016
+    /// This state MUST be in the body fixed frame (e.g. ITRF93) prior to calling this function, or the computation is **invalid**.
```
Comment (ChristopherRabotin) [inline anise/src/astro/orbit_geodetic.rs:231]: Rename the `geodetic_*` functions to not have that extra name and clarify that the latitude and longitude are always geodetic in the comments.

File: anise/tests/ephemerides/transform.rs [hunk 3]
```diff
@@ -140,3 +140,49 @@ fn de440s_transform_verif_venus2emb() {
     spice::unload(bpc_path);
     spice::unload(spk_path);
 }
+
+#[test]
+fn specific_test() {
```
Comment (ChristopherRabotin) [inline anise/tests/ephemerides/transform.rs:145]:
```suggestion
fn spice_verif_iau_moon() {
```

File: anise/tests/ephemerides/transform.rs [hunk 4]
```diff
@@ -140,3 +140,49 @@ fn de440s_transform_verif_venus2emb() {
...
+        IAU_MOON_FRAME,
+    );
+
+    println!("ANISE\n{anise_iau_moon}\nSPICE\n{spice_iau_moon}");
+    let rss_pos_km = anise_iau_moon.rss_radius_km(&spice_iau_moon).unwrap();
+    let rss_vel_km_s = anise_iau_moon.rss_velocity_km_s(&spice_iau_moon).unwrap();
+
+    dbg!(rss_pos_km, rss_vel_km_s);
+
+    assert!(rss_pos_km < 0.01);
```
Comment (ChristopherRabotin) [inline anise/tests/ephemerides/transform.rs:186]: Comment why the error is 10 meters!

File: anise/tests/orientations/mod.rs [hunk 5]
```diff
@@ -208,3 +210,93 @@ fn test_j2k_to_itrf93() {
         dcm.rot_mat_dt.unwrap() - spice_dcm.rot_mat_dt.unwrap()
     );
 }
+
+/// The IAU_MOON frame rotation differs from SPICE by a norm of 4.1e-6.
```
Comment (ChristopherRabotin) [inline anise/tests/orientations/mod.rs:214]: Add this information to a README on validation.

File: anise/tests/orientations/validation.rs [hunk 6]
```diff
@@ -121,7 +128,8 @@ fn validate_iau_rotation_to_parent() {
                 rot_mat_dt,
             };
 
-            if num == 0 {
+            // Print out the error at its greatest.
```
Comment (ChristopherRabotin) [inline anise/tests/orientations/validation.rs:131]:
```suggestion
            // Print out the error at its greatest, since we're the furthest away from J2000 reference epoch.
```

File: anise/src/astro/orbit_geodetic.rs (hunk 1 above)
Comment (ChristopherRabotin) [reply anise/src/astro/orbit_geodetic.rs:198]: The equations are not homogeneous.
